<a href="https://colab.research.google.com/github/anjusree123/TensorFlow/blob/main/Tensors_and_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
strings= tf.Variable(["Hello World"],tf.string)
floats=tf.Variable([3.14159,2.71828],tf.float64)
ints=tf.Variable([1,2,3],tf.int32)
complexs=tf.Variable([25.9-7.39j,1.23-4.91j],tf.complex128)

In [3]:
tf.Variable(tf.constant(4.2,shape=(3,3)))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2]], dtype=float32)>

In [4]:
v=tf.Variable(0.0)
w=v+1
print(type(w))


<class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
v.assign_add(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [6]:
v.assign_sub(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


In [ ]:
x=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print("dtype:",x.dtype)
print("shape:", x.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
dtype: <dtype: 'int32'>
shape: (3, 3)


In [ ]:
x.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [ ]:
x=tf.constant([[1,2,3],[4,5,6],[7,8,9]],dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


In [ ]:
coeffs=np.arange(16)

In [ ]:
shape1=[8,2]
shape2=[4,4]
shape3=[2,2,2,2]

In [ ]:
a=tf.constant(coeffs,shape=shape1)
print("\n a:\n", a)
b=tf.constant(coeffs,shape=shape2)
print("\n b: \n", b)
c=tf.constant(coeffs,shape=shape3)
print("\n c: \n", c)


 a:
 tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]], shape=(8, 2), dtype=int64)

 b: 
 tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int64)

 c: 
 tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]], shape=(2, 2, 2, 2), dtype=int64)


In [7]:
t=tf.constant(np.arange(80),shape=[5,2,8])

In [8]:
rank=tf.rank(t)

In [9]:
print("rank",rank)

rank tf.Tensor(3, shape=(), dtype=int32)


In [10]:
t2=tf.reshape(t,[8,10])

In [11]:
print("t2.shape",t2.shape)

t2.shape (8, 10)


In [12]:
ones=tf.ones(shape=(2,3))
zeros=tf.zeros(shape=(2,3))
eye=tf.eye(3)
tensor7=tf.constant(7.0,shape=[2,2])

In [13]:
print("\n Ones: \n", ones)
print("\n Zeros:\n", zeros)
print("\n Identity:\n", eye)
print("\n Tensor filled with 7:", tensor7)


 Ones: 
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

 Zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

 Identity:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)

 Tensor filled with 7: tf.Tensor(
[[7. 7.]
 [7. 7.]], shape=(2, 2), dtype=float32)


In [14]:
t1=tf.ones(shape=(2,2))
t2=tf.zeros(shape=(2,2))

In [16]:
concat0=tf.concat([t1,t2],0)
concat1=tf.concat([t1,t2],1)

In [17]:
print(concat0)
print(concat1)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]], shape=(2, 4), dtype=float32)


In [18]:
t=tf.constant(np.arange(24),shape=(3,2,4))
print("\n shape",t.shape)


 shape (3, 2, 4)


In [19]:
t1=tf.expand_dims(t,0)
t2=tf.expand_dims(t,1)
t3=tf.expand_dims(t,3)

In [20]:
print("\n After expanding dims\n t1 shape:", t1.shape,"\n t2 shape:",t2.shape,"t3.shape:",t3.shape)


 After expanding dims
 t1 shape: (1, 3, 2, 4) 
 t2 shape: (3, 1, 2, 4) t3.shape: (3, 2, 4, 1)


In [21]:
t1=tf.squeeze(t1,0)
t2=tf.squeeze(t2,1)
t3=tf.squeeze(t3,3)

In [22]:
print("\n After squeezing \n t1.shape:",t1.shape, "\n t2 shape:",t2.shape,"t3 shape:",t3.shape)


 After squeezing 
 t1.shape: (3, 2, 4) 
 t2 shape: (3, 2, 4) t3 shape: (3, 2, 4)


In [24]:
c=tf.constant([[1.0,2.0],[3.0,4.0]])
d=tf.constant([[1.0,1.0],[0.0,1.0]])

In [25]:
matmul_cd=tf.matmul(c,d)
print(matmul_cd)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


In [28]:
tn=tf.random.normal(shape=(2,2),mean=0,stddev=1.)
tu=tf.random.uniform(shape=(2,1),minval=0,maxval=10, dtype='int32')
tp=tf.random.poisson((2,2),5)

In [29]:
d=tf.square(tn)
e=tf.exp(d)
f=tf.cos(c)